name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # 触发条件：tag 以 v 开头（如 v1.0.0）

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # 选择你的 .NET 版本

      - name: Clear NuGet Cache
        run: dotnet nuget locals all --clear  # 清理缓存，避免影响构建

      - name: Restore dependencies (Ignore Test Projects)
        run: |
          find AnotherQbittorrent -name "*.csproj" -not -path "*Test*" | xargs -I {} dotnet restore {}

      - name: Build project
        run: dotnet build AnotherQbittorrent/AnotherQbittorrent.csproj --configuration Release --no-restore

      - name: Create NuGet package
        run: dotnet pack AnotherQbittorrent/AnotherQbittorrent.csproj --configuration Release --no-build --output nupkg

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
