name: Publish NuGet Package

on:
    push:
        tags:
            - "v*" # 触发条件：tag 以 v 开头（如 v1.0.0）

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x # 替换为你的 .NET 版本

            - name: Extract version from tag
              id: get_version
              run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

            - name: Update project file with new version
              run: |
                  sed -i 's/<Version>.*<\/Version>/<Version>'"$VERSION"'<\/Version>/' AnotherQbittorrent/AnotherQbittorrent.csproj

            - name: Restore dependencies
              run: dotnet restore AnotherQbittorrent/AnotherQbittorrent.csproj

            - name: Build project
              run: dotnet build AnotherQbittorrent/AnotherQbittorrent.csproj --configuration Release --no-restore

            - name: Create NuGet package
              run: dotnet pack AnotherQbittorrent/AnotherQbittorrent.csproj --configuration Release --no-build --output nupkg

            - name: Publish to NuGet
              env:
                  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
              run: |
                  dotnet nuget push nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
